---
email :
  emailFrom : "foo@gmail.com"
  secret : "bar"
  listOfEmailsTo :
    - "user1@gmail.com"
    - "user2@gmail.com"
listOfEndPoints:
  "PcDiga" :
    - "www.pcdiga.com/graphics1"
    - "www.pcdiga.com/graphics2"
  "PcComponentes" :
    - "www.pccomponentes.com/graphics1"
    - "www.pccomponentes.com/graphics2"